// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChatMessage {
    "role": string;
    "content": string;
    "reasoning_content": string;
    "tool_calls"?: ToolCall[];
    "tool_call_id"?: string;
    "name"?: string;
    "token_usage"?: Usage | null;

    /** Creates a new ChatMessage instance. */
    constructor($$source: Partial<ChatMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("reasoning_content" in $$source)) {
            this["reasoning_content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessage {
        const $$createField3_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool_calls" in $$parsedSource) {
            $$parsedSource["tool_calls"] = $$createField3_0($$parsedSource["tool_calls"]);
        }
        if ("token_usage" in $$parsedSource) {
            $$parsedSource["token_usage"] = $$createField6_0($$parsedSource["token_usage"]);
        }
        return new ChatMessage($$parsedSource as Partial<ChatMessage>);
    }
}

export class Model {
    "ID": string;
    "DisplayName": string;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("DisplayName" in $$source)) {
            this["DisplayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

export class SkillMeta {
    "name": string;
    "description": string;
    "path": string;

    /**
     * "project-opencode" | "project-claude" | "project-agents" | "global-monika" | "global-claude" | "global-agents" | "manual"
     */
    "source": string;
    "enabled"?: boolean | null;

    /** Creates a new SkillMeta instance. */
    constructor($$source: Partial<SkillMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillMeta($$parsedSource as Partial<SkillMeta>);
    }
}

export class ToolCall {
    "id": string;
    "type": string;
    "function": ToolCallFunc;

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            this["function"] = (new ToolCallFunc());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("function" in $$parsedSource) {
            $$parsedSource["function"] = $$createField2_0($$parsedSource["function"]);
        }
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

export class ToolCallFunc {
    "name": string;
    "arguments": string;

    /** Creates a new ToolCallFunc instance. */
    constructor($$source: Partial<ToolCallFunc> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallFunc instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallFunc {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallFunc($$parsedSource as Partial<ToolCallFunc>);
    }
}

export class Usage {
    "input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "reasoning_tokens": number;
    "cache_read_tokens": number;
    "cache_write_tokens": number;

    /** Creates a new Usage instance. */
    constructor($$source: Partial<Usage> = {}) {
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("cache_write_tokens" in $$source)) {
            this["cache_write_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     */
    static createFrom($$source: any = {}): Usage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage($$parsedSource as Partial<Usage>);
    }
}

// Private type creation functions
const $$createType0 = ToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Usage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = ToolCallFunc.createFrom;
