// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChatMessage {
    /**
     * Creates a new ChatMessage instance.
     * @param {Partial<ChatMessage>} [$$source = {}] - The source object to create the ChatMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("reasoning_content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reasoning_content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ToolCall[] | undefined}
             */
            this["tool_calls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tool_call_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Usage | null | undefined}
             */
            this["token_usage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {QuotedMessage[] | undefined}
             */
            this["quoted_messages"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatMessage}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool_calls" in $$parsedSource) {
            $$parsedSource["tool_calls"] = $$createField3_0($$parsedSource["tool_calls"]);
        }
        if ("token_usage" in $$parsedSource) {
            $$parsedSource["token_usage"] = $$createField6_0($$parsedSource["token_usage"]);
        }
        if ("quoted_messages" in $$parsedSource) {
            $$parsedSource["quoted_messages"] = $$createField7_0($$parsedSource["quoted_messages"]);
        }
        return new ChatMessage(/** @type {Partial<ChatMessage>} */($$parsedSource));
    }
}

export class Model {
    /**
     * Creates a new Model instance.
     * @param {Partial<Model>} [$$source = {}] - The source object to create the Model.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("DisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DisplayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Model}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model(/** @type {Partial<Model>} */($$parsedSource));
    }
}

/**
 * QuotedMessage is a snapshot of a referenced message used for quoting/forwarding.
 */
export class QuotedMessage {
    /**
     * Creates a new QuotedMessage instance.
     * @param {Partial<QuotedMessage>} [$$source = {}] - The source object to create the QuotedMessage.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuotedMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuotedMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuotedMessage(/** @type {Partial<QuotedMessage>} */($$parsedSource));
    }
}

export class SkillMeta {
    /**
     * Creates a new SkillMeta instance.
     * @param {Partial<SkillMeta>} [$$source = {}] - The source object to create the SkillMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "project-opencode" | "project-claude" | "project-agents" | "global-monika" | "global-claude" | "global-agents" | "manual"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["enabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillMeta(/** @type {Partial<SkillMeta>} */($$parsedSource));
    }
}

export class ToolCall {
    /**
     * Creates a new ToolCall instance.
     * @param {Partial<ToolCall>} [$$source = {}] - The source object to create the ToolCall.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            /**
             * @member
             * @type {ToolCallFunc}
             */
            this["function"] = (new ToolCallFunc());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCall}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("function" in $$parsedSource) {
            $$parsedSource["function"] = $$createField2_0($$parsedSource["function"]);
        }
        return new ToolCall(/** @type {Partial<ToolCall>} */($$parsedSource));
    }
}

export class ToolCallFunc {
    /**
     * Creates a new ToolCallFunc instance.
     * @param {Partial<ToolCallFunc>} [$$source = {}] - The source object to create the ToolCallFunc.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("arguments" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arguments"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallFunc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCallFunc}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallFunc(/** @type {Partial<ToolCallFunc>} */($$parsedSource));
    }
}

export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("input_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_read_tokens"] = 0;
        }
        if (!("cache_write_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_write_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Usage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = QuotedMessage.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ToolCallFunc.createFrom;
