// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChatMessage {
    /**
     * Creates a new ChatMessage instance.
     * @param {Partial<ChatMessage>} [$$source = {}] - The source object to create the ChatMessage.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("reasoning_content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reasoning_content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ToolCall[] | undefined}
             */
            this["tool_calls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tool_call_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatMessage}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool_calls" in $$parsedSource) {
            $$parsedSource["tool_calls"] = $$createField3_0($$parsedSource["tool_calls"]);
        }
        return new ChatMessage(/** @type {Partial<ChatMessage>} */($$parsedSource));
    }
}

export class Model {
    /**
     * Creates a new Model instance.
     * @param {Partial<Model>} [$$source = {}] - The source object to create the Model.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("DisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DisplayName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Model}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model(/** @type {Partial<Model>} */($$parsedSource));
    }
}

export class ToolCall {
    /**
     * Creates a new ToolCall instance.
     * @param {Partial<ToolCall>} [$$source = {}] - The source object to create the ToolCall.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            /**
             * @member
             * @type {ToolCallFunc}
             */
            this["function"] = (new ToolCallFunc());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCall}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("function" in $$parsedSource) {
            $$parsedSource["function"] = $$createField2_0($$parsedSource["function"]);
        }
        return new ToolCall(/** @type {Partial<ToolCall>} */($$parsedSource));
    }
}

export class ToolCallFunc {
    /**
     * Creates a new ToolCallFunc instance.
     * @param {Partial<ToolCallFunc>} [$$source = {}] - The source object to create the ToolCallFunc.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("arguments" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arguments"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallFunc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCallFunc}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallFunc(/** @type {Partial<ToolCallFunc>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ToolCallFunc.createFrom;
