// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasUpdate"] = false;
        }
        if (!("releaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseURL"] = "";
        }
        if (!("downloadURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadURL"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseNotes"] = "";
        }
        if (!("assetSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["assetSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

export class UpdateStatus {
    /**
     * Creates a new UpdateStatus instance.
     * @param {Partial<UpdateStatus>} [$$source = {}] - The source object to create the UpdateStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UpdateInfo | null | undefined}
             */
            this["updateInfo"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updateInfo" in $$parsedSource) {
            $$parsedSource["updateInfo"] = $$createField3_0($$parsedSource["updateInfo"]);
        }
        return new UpdateStatus(/** @type {Partial<UpdateStatus>} */($$parsedSource));
    }
}

export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("commitSha" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commitSha"] = "";
        }
        if (!("buildTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
