// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UpdateInfo {
    "currentVersion": string;
    "latestVersion": string;
    "hasUpdate": boolean;
    "releaseURL": string;
    "downloadURL": string;
    "releaseNotes": string;
    "assetSize": number;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("releaseURL" in $$source)) {
            this["releaseURL"] = "";
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

export class UpdateStatus {
    "state": string;
    "progress": number;
    "message": string;
    "updateInfo"?: UpdateInfo | null;

    /** Creates a new UpdateStatus instance. */
    constructor($$source: Partial<UpdateStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateStatus {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updateInfo" in $$parsedSource) {
            $$parsedSource["updateInfo"] = $$createField3_0($$parsedSource["updateInfo"]);
        }
        return new UpdateStatus($$parsedSource as Partial<UpdateStatus>);
    }
}

export class VersionInfo {
    "version": string;
    "commitSha": string;
    "buildTime": string;

    /** Creates a new VersionInfo instance. */
    constructor($$source: Partial<VersionInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commitSha" in $$source)) {
            this["commitSha"] = "";
        }
        if (!("buildTime" in $$source)) {
            this["buildTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo($$parsedSource as Partial<VersionInfo>);
    }
}

// Private type creation functions
const $$createType0 = UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
