// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PermissionRequiredEvent is sent from backend to frontend when Stage 3 is reached.
 */
export class PermissionRequiredEvent {
    /**
     * Creates a new PermissionRequiredEvent instance.
     * @param {Partial<PermissionRequiredEvent>} [$$source = {}] - The source object to create the PermissionRequiredEvent.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "permission_required"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("tool" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["args"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * "auto" or "manual"
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("requestId" in $$source)) {
            /**
             * unique ID for correlating response
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionRequiredEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionRequiredEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionRequiredEvent(/** @type {Partial<PermissionRequiredEvent>} */($$parsedSource));
    }
}

/**
 * PermissionResponse is sent from frontend to backend.
 */
export class PermissionResponse {
    /**
     * Creates a new PermissionResponse instance.
     * @param {Partial<PermissionResponse>} [$$source = {}] - The source object to create the PermissionResponse.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * "allow", "deny", "allow_always"
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rulePattern"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionResponse(/** @type {Partial<PermissionResponse>} */($$parsedSource));
    }
}

/**
 * Pipeline ties together HardRuleEngine and ConfirmUI into a single permission
 * check orchestrator. The mode (Auto / Manual) controls the default action when
 * no user rule matches.
 */
export class Pipeline {
    /**
     * Creates a new Pipeline instance.
     * @param {Partial<Pipeline>} [$$source = {}] - The source object to create the Pipeline.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pipeline instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Pipeline}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pipeline(/** @type {Partial<Pipeline>} */($$parsedSource));
    }
}

/**
 * Rule is a single permission rule. Source indicates origin: builtin, global, or project.
 */
export class Rule {
    /**
     * Creates a new Rule instance.
     * @param {Partial<Rule>} [$$source = {}] - The source object to create the Rule.
     */
    constructor($$source = {}) {
        if (!("tool" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool"] = "";
        }
        if (!("pattern" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pattern"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * "allow" or "deny"
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "builtin", "user_manual", "user_always"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["createdAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rule(/** @type {Partial<Rule>} */($$parsedSource));
    }
}
