// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PermissionRequiredEvent is sent from backend to frontend when Stage 3 is reached.
 */
export class PermissionRequiredEvent {
    /**
     * "permission_required"
     */
    "type": string;
    "sessionId": string;
    "tool": string;
    "args": string;
    "reason": string;

    /**
     * "auto" or "manual"
     */
    "mode": string;

    /**
     * unique ID for correlating response
     */
    "requestId": string;

    /** Creates a new PermissionRequiredEvent instance. */
    constructor($$source: Partial<PermissionRequiredEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionRequiredEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionRequiredEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionRequiredEvent($$parsedSource as Partial<PermissionRequiredEvent>);
    }
}

/**
 * PermissionResponse is sent from frontend to backend.
 */
export class PermissionResponse {
    "requestId": string;

    /**
     * "allow", "deny", "allow_always"
     */
    "decision": string;
    "rulePattern"?: string;

    /** Creates a new PermissionResponse instance. */
    constructor($$source: Partial<PermissionResponse> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("decision" in $$source)) {
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionResponse($$parsedSource as Partial<PermissionResponse>);
    }
}

/**
 * Pipeline ties together HardRuleEngine and ConfirmUI into a single permission
 * check orchestrator. The mode (Auto / Manual) controls the default action when
 * no user rule matches.
 */
export class Pipeline {

    /** Creates a new Pipeline instance. */
    constructor($$source: Partial<Pipeline> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pipeline instance from a string or object.
     */
    static createFrom($$source: any = {}): Pipeline {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pipeline($$parsedSource as Partial<Pipeline>);
    }
}

/**
 * Rule is a single permission rule. Source indicates origin: builtin, global, or project.
 */
export class Rule {
    "tool": string;
    "pattern": string;

    /**
     * "allow" or "deny"
     */
    "decision": string;

    /**
     * "builtin", "user_manual", "user_always"
     */
    "source": string;
    "createdAt"?: string;

    /** Creates a new Rule instance. */
    constructor($$source: Partial<Rule> = {}) {
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("decision" in $$source)) {
            this["decision"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rule instance from a string or object.
     */
    static createFrom($$source: any = {}): Rule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Rule($$parsedSource as Partial<Rule>);
    }
}
