// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";

/**
 * ChildSession holds the result of a completed child agent run.
 */
export class ChildSession {
    /**
     * Creates a new ChildSession instance.
     * @param {Partial<ChildSession>} [$$source = {}] - The source object to create the ChildSession.
     */
    constructor($$source = {}) {
        if (!("Messages" in $$source)) {
            /**
             * @member
             * @type {engine$0.ChatMessage[]}
             */
            this["Messages"] = [];
        }
        if (!("Agent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Agent"] = "";
        }
        if (!("ParentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ParentID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("TokenCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["TokenCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChildSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChildSession}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Messages" in $$parsedSource) {
            $$parsedSource["Messages"] = $$createField0_0($$parsedSource["Messages"]);
        }
        return new ChildSession(/** @type {Partial<ChildSession>} */($$parsedSource));
    }
}

export class CompactingEvent {
    /**
     * Creates a new CompactingEvent instance.
     * @param {Partial<CompactingEvent>} [$$source = {}] - The source object to create the CompactingEvent.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompactingEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompactingEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompactingEvent(/** @type {Partial<CompactingEvent>} */($$parsedSource));
    }
}

export class CompactionEvent {
    /**
     * Creates a new CompactionEvent instance.
     * @param {Partial<CompactionEvent>} [$$source = {}] - The source object to create the CompactionEvent.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("before_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["before_tokens"] = 0;
        }
        if (!("after_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["after_tokens"] = 0;
        }
        if (!("compaction_num" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compaction_num"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompactionEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompactionEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompactionEvent(/** @type {Partial<CompactionEvent>} */($$parsedSource));
    }
}

/**
 * TaskItem is a lightweight task representation for frontend events.
 * Mirrors the fields of tool.Task without importing the tool package.
 */
export class TaskItem {
    /**
     * Creates a new TaskItem instance.
     * @param {Partial<TaskItem>} [$$source = {}] - The source object to create the TaskItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["blockedBy"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskItem}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockedBy" in $$parsedSource) {
            $$parsedSource["blockedBy"] = $$createField4_0($$parsedSource["blockedBy"]);
        }
        return new TaskItem(/** @type {Partial<TaskItem>} */($$parsedSource));
    }
}

export class ToolEvent {
    /**
     * Creates a new ToolEvent instance.
     * @param {Partial<ToolEvent>} [$$source = {}] - The source object to create the ToolEvent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEvent(/** @type {Partial<ToolEvent>} */($$parsedSource));
    }
}

export class UsageEvent {
    /**
     * Creates a new UsageEvent instance.
     * @param {Partial<UsageEvent>} [$$source = {}] - The source object to create the UsageEvent.
     */
    constructor($$source = {}) {
        if (!("input_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_read_tokens"] = 0;
        }
        if (!("cache_write_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_write_tokens"] = 0;
        }
        if (!("context_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["context_tokens"] = 0;
        }
        if (!("max_context" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_context"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageEvent(/** @type {Partial<UsageEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = engine$0.ChatMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
