// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ToolEvent {
    "id": string;
    "name": string;
    "input": string;
    "output": string;
    "status": string;

    /** Creates a new ToolEvent instance. */
    constructor($$source: Partial<ToolEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEvent($$parsedSource as Partial<ToolEvent>);
    }
}

export class UsageEvent {
    "input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "reasoning_tokens": number;
    "cache_read_tokens": number;
    "cache_write_tokens": number;
    "context_tokens": number;
    "max_context": number;

    /** Creates a new UsageEvent instance. */
    constructor($$source: Partial<UsageEvent> = {}) {
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("cache_write_tokens" in $$source)) {
            this["cache_write_tokens"] = 0;
        }
        if (!("context_tokens" in $$source)) {
            this["context_tokens"] = 0;
        }
        if (!("max_context" in $$source)) {
            this["max_context"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageEvent($$parsedSource as Partial<UsageEvent>);
    }
}
