// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";

export class Agent {
    "name": string;
    "description"?: string;
    "systemPrompt"?: string;

    /**
     * "provider/model"，空则继承
     */
    "model"?: string;

    /**
     * 保留兼容
     */
    "provider"?: string;

    /**
     * nil 用默认
     */
    "temperature"?: number | null;
    "hidden"?: boolean;

    /**
     * 内置 agent 被 config 禁用
     */
    "disabled"?: boolean;

    /**
     * tool → allow/ask/deny
     */
    "permission"?: { [_ in string]?: string };
    "isCustom": boolean;

    /**
     * "builtin" | "custom"
     */
    "source": string;

    /** Creates a new Agent instance. */
    constructor($$source: Partial<Agent> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isCustom" in $$source)) {
            this["isCustom"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Agent instance from a string or object.
     */
    static createFrom($$source: any = {}): Agent {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField8_0($$parsedSource["permission"]);
        }
        return new Agent($$parsedSource as Partial<Agent>);
    }
}

/**
 * ChildSession holds the result of a completed child agent run.
 */
export class ChildSession {
    "Messages": engine$0.ChatMessage[];
    "Agent": string;
    "ParentID": string;
    "Title": string;
    "TokenCount": number;

    /** Creates a new ChildSession instance. */
    constructor($$source: Partial<ChildSession> = {}) {
        if (!("Messages" in $$source)) {
            this["Messages"] = [];
        }
        if (!("Agent" in $$source)) {
            this["Agent"] = "";
        }
        if (!("ParentID" in $$source)) {
            this["ParentID"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("TokenCount" in $$source)) {
            this["TokenCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChildSession instance from a string or object.
     */
    static createFrom($$source: any = {}): ChildSession {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Messages" in $$parsedSource) {
            $$parsedSource["Messages"] = $$createField0_0($$parsedSource["Messages"]);
        }
        return new ChildSession($$parsedSource as Partial<ChildSession>);
    }
}

export class CompactionEvent {
    "summary": string;
    "before_tokens": number;
    "after_tokens": number;
    "compaction_num": number;

    /** Creates a new CompactionEvent instance. */
    constructor($$source: Partial<CompactionEvent> = {}) {
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("before_tokens" in $$source)) {
            this["before_tokens"] = 0;
        }
        if (!("after_tokens" in $$source)) {
            this["after_tokens"] = 0;
        }
        if (!("compaction_num" in $$source)) {
            this["compaction_num"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompactionEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): CompactionEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompactionEvent($$parsedSource as Partial<CompactionEvent>);
    }
}

export type LoopOption = any;

/**
 * TaskItem is a lightweight task representation for frontend events.
 * Mirrors the fields of tool.Task without importing the tool package.
 */
export class TaskItem {
    "id": string;
    "subject": string;
    "description"?: string;
    "status": string;
    "blockedBy"?: string[];

    /** Creates a new TaskItem instance. */
    constructor($$source: Partial<TaskItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskItem {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockedBy" in $$parsedSource) {
            $$parsedSource["blockedBy"] = $$createField4_0($$parsedSource["blockedBy"]);
        }
        return new TaskItem($$parsedSource as Partial<TaskItem>);
    }
}

export class ToolEvent {
    "id": string;
    "name": string;
    "input": string;
    "output": string;
    "status": string;
    "diffLines"?: string[];

    /** Creates a new ToolEvent instance. */
    constructor($$source: Partial<ToolEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolEvent($$parsedSource as Partial<ToolEvent>);
    }
}

export class UsageEvent {
    "input_tokens": number;
    "output_tokens": number;
    "total_tokens": number;
    "reasoning_tokens": number;
    "cache_read_tokens": number;
    "cache_write_tokens": number;
    "context_tokens": number;
    "max_context": number;

    /** Creates a new UsageEvent instance. */
    constructor($$source: Partial<UsageEvent> = {}) {
        if (!("input_tokens" in $$source)) {
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            this["cache_read_tokens"] = 0;
        }
        if (!("cache_write_tokens" in $$source)) {
            this["cache_write_tokens"] = 0;
        }
        if (!("context_tokens" in $$source)) {
            this["context_tokens"] = 0;
        }
        if (!("max_context" in $$source)) {
            this["max_context"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageEvent($$parsedSource as Partial<UsageEvent>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = engine$0.ChatMessage.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
