// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivateSession activates the main window and returns the session ID for the given notification.
 * @param {string} notifID
 * @returns {$CancellablePromise<string>}
 */
export function ActivateSession(notifID) {
    return $Call.ByID(3863691755, notifID);
}

/**
 * AddPermissionRule adds a new permission rule.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function AddPermissionRule(args) {
    return $Call.ByID(621401762, args);
}

/**
 * AddSkillPath appends a directory to the skill search paths.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function AddSkillPath(args) {
    return $Call.ByID(110335, args);
}

/**
 * AppendLoopOption appends a loop option to the internally stored slice.
 * @param {agent$0.LoopOption} opt
 * @returns {$CancellablePromise<void>}
 */
export function AppendLoopOption(opt) {
    return $Call.ByID(1912792643, opt);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveSession(projectPath, sessionID) {
    return $Call.ByID(457154186, projectPath, sessionID);
}

/**
 * AskUser sends a question to the frontend and blocks until the user responds.
 * @param {string} sessionID
 * @param {string} question
 * @param {string} title
 * @param {string[]} options
 * @returns {$CancellablePromise<string>}
 */
export function AskUser(sessionID, question, title, options) {
    return $Call.ByID(641074198, sessionID, question, title, options);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CancelGeneration(sessionID) {
    return $Call.ByID(2154546860, sessionID);
}

/**
 * CancelPopupHide stops the popup hide debounce.
 * @returns {$CancellablePromise<void>}
 */
export function CancelPopupHide() {
    return $Call.ByID(4142447236);
}

/**
 * CheckForUpdate checks GitHub for the latest release.
 * @returns {$CancellablePromise<update$0.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(283735038).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearTrayNotifications clears all notifications and stops blink.
 * @returns {$CancellablePromise<void>}
 */
export function ClearTrayNotifications() {
    return $Call.ByID(3313674999);
}

/**
 * @param {string} projectPath
 * @param {string} srcPath
 * @param {string} destDir
 * @returns {$CancellablePromise<void>}
 */
export function CopyItem(projectPath, srcPath, destDir) {
    return $Call.ByID(3645916758, projectPath, srcPath, destDir);
}

/**
 * CreateBranch creates and checks out a new branch from the given base branch.
 * @param {string} projectPath
 * @param {string} name
 * @param {string} baseBranch
 * @returns {$CancellablePromise<void>}
 */
export function CreateBranch(projectPath, name, baseBranch) {
    return $Call.ByID(2177215684, projectPath, name, baseBranch);
}

/**
 * @param {string} projectPath
 * @param {string} dirPath
 * @returns {$CancellablePromise<void>}
 */
export function CreateDir(projectPath, dirPath) {
    return $Call.ByID(1156687635, projectPath, dirPath);
}

/**
 * DeleteAgent disables an agent by name (soft-delete via Disabled flag).
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAgent(args) {
    return $Call.ByID(3042182576, args);
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteItem(projectPath, filePath) {
    return $Call.ByID(1892823524, projectPath, filePath);
}

/**
 * DeleteMCPServer removes an MCP server entry from config by ID.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMCPServer(args) {
    return $Call.ByID(2274596006, args);
}

/**
 * DeletePermissionRule removes a rule identified by tool, pattern, and source.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function DeletePermissionRule(args) {
    return $Call.ByID(2803374586, args);
}

/**
 * DeleteProvider removes a model provider from config by ID.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProvider(args) {
    return $Call.ByID(3540968018, args);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(projectPath, sessionID) {
    return $Call.ByID(1674819245, projectPath, sessionID);
}

/**
 * DismissNotification removes a single notification without activating.
 * @param {string} notifID
 * @returns {$CancellablePromise<void>}
 */
export function DismissNotification(notifID) {
    return $Call.ByID(3122295347, notifID);
}

/**
 * DownloadUpdate downloads the update for the given URL.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function DownloadUpdate(args) {
    return $Call.ByID(2973123721, args);
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function DuplicateItem(projectPath, filePath) {
    return $Call.ByID(1041153378, projectPath, filePath);
}

/**
 * @param {string} sessionID
 * @param {agent$0.TaskItem[]} tasks
 * @returns {$CancellablePromise<void>}
 */
export function EmitTaskEvent(sessionID, tasks) {
    return $Call.ByID(1268878478, sessionID, tasks);
}

/**
 * GetAppVersion returns the application version information.
 * @returns {$CancellablePromise<update$0.VersionInfo>}
 */
export function GetAppVersion() {
    return $Call.ByID(4174589881).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetAvailableProviders returns all providers available from models.dev catalog.
 * This is used in the Settings UI to let users select a provider to add.
 * @returns {$CancellablePromise<$models.AvailableProviderInfo[]>}
 */
export function GetAvailableProviders() {
    return $Call.ByID(2025681215).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function GetCurrentProject() {
    return $Call.ByID(4211252234).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetDefaultModel() {
    return $Call.ByID(3464228622).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.DiffResult | null>}
 */
export function GetFileDiff(projectPath, filePath) {
    return $Call.ByID(3432667145, projectPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @param {string} oldContent
 * @returns {$CancellablePromise<$models.DiffResult | null>}
 */
export function GetInlineDiff(projectPath, filePath, oldContent) {
    return $Call.ByID(2333122030, projectPath, filePath, oldContent).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} providerID
 * @returns {$CancellablePromise<engine$0.Model[]>}
 */
export function GetModels(providerID) {
    return $Call.ByID(2740169318, providerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetProjectPath returns the current project directory (exported for use by tools).
 * @returns {$CancellablePromise<string>}
 */
export function GetProjectPath() {
    return $Call.ByID(2154343474);
}

/**
 * @returns {$CancellablePromise<$models.ProviderInfo[]>}
 */
export function GetProviders() {
    return $Call.ByID(2466924902).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetRecentProjects returns recently opened projects from ~/.monika/recent.json.
 * @returns {$CancellablePromise<$models.RecentProject[]>}
 */
export function GetRecentProjects() {
    return $Call.ByID(541402157).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetSkillContent returns the SKILL.md content and sibling files for a given skill name.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<$models.SkillContentResult>}
 */
export function GetSkillContent(args) {
    return $Call.ByID(3735502862, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetTrayNotifications returns notifications for the popup window.
 * @returns {$CancellablePromise<$models.NotificationData[]>}
 */
export function GetTrayNotifications() {
    return $Call.ByID(1300659496).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetUpdateStatus returns the current update process status.
 * @returns {$CancellablePromise<update$0.UpdateStatus>}
 */
export function GetUpdateStatus() {
    return $Call.ByID(1060979343).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * ImportMCPServers parses a standard mcpServers JSON block and adds the servers to config.
 * The input format is: { "mcpServers": { "name": { "type": "stdio", "command": "...", ... } } }
 * Returns the list of server IDs that were imported.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<string[]>}
 */
export function ImportMCPServers(args) {
    return $Call.ByID(2481263241, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * InstallSkillFromURL downloads a GitHub repo and installs skills found in it.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<string[]>}
 */
export function InstallSkillFromURL(args) {
    return $Call.ByID(3775411401, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * InstallSkillFromZip installs skills from a base64-encoded ZIP file.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<string[]>}
 */
export function InstallSkillFromZip(args) {
    return $Call.ByID(165010839, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * InstallUpdate replaces the current binary and restarts.
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate() {
    return $Call.ByID(1856021770);
}

/**
 * ListAgents returns all registered agents.
 * @returns {$CancellablePromise<agent$0.Agent[]>}
 */
export function ListAgents() {
    return $Call.ByID(1523826198).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * ListBranches returns local and remote git branches for the given project.
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.BranchInfo[]>}
 */
export function ListBranches(projectPath) {
    return $Call.ByID(2066625236, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.ChangeStat[]>}
 */
export function ListChangeStats(projectPath) {
    return $Call.ByID(2025730651, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * ListDirectory returns the non-recursive contents of a directory.
 * @param {string} parentPath
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function ListDirectory(parentPath) {
    return $Call.ByID(2022278691, parentPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * ListDrives returns available drive roots on Windows, or empty on other platforms.
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function ListDrives() {
    return $Call.ByID(2497242737).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.FileChange[]>}
 */
export function ListFileChanges(projectPath) {
    return $Call.ByID(3265914211, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {boolean} showHidden
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function ListFileTree(projectPath, showHidden) {
    return $Call.ByID(2046651834, projectPath, showHidden).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MCPServerInfo[]>}
 */
export function ListMCPServers() {
    return $Call.ByID(2784883516).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * ListPermissionRules returns all permission rules for the given project,
 * including both built-in blacklist rules and user-defined rules.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<permission$0.Rule[]>}
 */
export function ListPermissionRules(args) {
    return $Call.ByID(1886094366, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProjectInfo[]>}
 */
export function ListProjects() {
    return $Call.ByID(1837161474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.SessionInfo[]>}
 */
export function ListSessions(projectPath) {
    return $Call.ByID(116118957, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @returns {$CancellablePromise<engine$0.SkillMeta[]>}
 */
export function ListSkills() {
    return $Call.ByID(4241996650).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * ListSystemCommands searches PATH for executable files matching prefix.
 * Returns up to 20 results, sorted alphabetically.
 * @param {string} prefix
 * @returns {$CancellablePromise<string[]>}
 */
export function ListSystemCommands(prefix) {
    return $Call.ByID(905674791, prefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * LoadChildSession returns a completed child agent session, or nil.
 * @param {string} sessionID
 * @returns {$CancellablePromise<agent$0.ChildSession | null>}
 */
export function LoadChildSession(sessionID) {
    return $Call.ByID(1226969414, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * LoadChildSessionFromDisk loads a completed child session from disk.
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<agent$0.ChildSession | null>}
 */
export function LoadChildSessionFromDisk(projectPath, sessionID) {
    return $Call.ByID(987540711, projectPath, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.Session | null>}
 */
export function LoadSession(projectPath, sessionID) {
    return $Call.ByID(665171952, projectPath, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * MakeDirectory creates a new directory at the given absolute path.
 * @param {string} parentPath
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function MakeDirectory(parentPath, name) {
    return $Call.ByID(3852488225, parentPath, name);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function MarkSessionViewed(projectPath, sessionID) {
    return $Call.ByID(4285813295, projectPath, sessionID);
}

/**
 * @param {string} projectPath
 * @param {string} providerID
 * @param {string} model
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function NewSession(projectPath, providerID, model) {
    return $Call.ByID(3342623882, projectPath, providerID, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(projectPath, filePath) {
    return $Call.ByID(1908588784, projectPath, filePath);
}

/**
 * OpenInFileManager opens the given directory path in the system file manager.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function OpenInFileManager(args) {
    return $Call.ByID(4046586048, args);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function OpenProject(path) {
    return $Call.ByID(2628211045, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * PendingChildSession stores a child session ID for a parent, so the frontend
 * can resolve it during execution (before the tool returns).
 * @param {string} parentID
 * @param {string} childID
 * @returns {$CancellablePromise<void>}
 */
export function PendingChildSession(parentID, childID) {
    return $Call.ByID(3382073829, parentID, childID);
}

/**
 * @param {string} providerID
 * @param {string} modelID
 * @returns {$CancellablePromise<void>}
 */
export function PersistSelection(providerID, modelID) {
    return $Call.ByID(4057758998, providerID, modelID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(2270927618);
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.FileContent | null>}
 */
export function ReadFile(projectPath, filePath) {
    return $Call.ByID(984933914, projectPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * ReconnectMCPServer disconnects and reconnects a configured MCP server,
 * then returns its available tool names.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<string[]>}
 */
export function ReconnectMCPServer(args) {
    return $Call.ByID(1193347248, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * RefreshBranch reads the current git branch from disk and updates in-memory state.
 * Returns the current branch name, or "—" if not a git repo.
 * @param {string} projectPath
 * @returns {$CancellablePromise<string>}
 */
export function RefreshBranch(projectPath) {
    return $Call.ByID(3999763195, projectPath);
}

/**
 * RemoveSkillPath removes a directory from the skill search paths.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSkillPath(args) {
    return $Call.ByID(2181192798, args);
}

/**
 * @param {string} projectPath
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function Rename(projectPath, oldPath, newPath) {
    return $Call.ByID(2146600506, projectPath, oldPath, newPath);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @param {string} newTitle
 * @returns {$CancellablePromise<void>}
 */
export function RenameSession(projectPath, sessionID, newTitle) {
    return $Call.ByID(3547192606, projectPath, sessionID, newTitle);
}

/**
 * RequestConfirm implements permission.ConfirmUI.
 * @param {permission$0.PermissionRequiredEvent} ev
 * @returns {$CancellablePromise<permission$0.PermissionResponse>}
 */
export function RequestConfirm(ev) {
    return $Call.ByID(1950638859, ev).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * ResolveChildSession returns the latest child session ID for a parent.
 * @param {string} parentID
 * @returns {$CancellablePromise<string>}
 */
export function ResolveChildSession(parentID) {
    return $Call.ByID(3285960262, parentID);
}

/**
 * RespondAskUser handles the frontend's response to an ask_user request.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function RespondAskUser(args) {
    return $Call.ByID(225985741, args);
}

/**
 * RespondPermission handles the frontend's response to a permission request.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function RespondPermission(args) {
    return $Call.ByID(3191520234, args);
}

/**
 * RunShellCommand executes a shell command in the project directory and returns merged stdout+stderr.
 * Commands timeout after 120 seconds.
 * @param {string} projectPath
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function RunShellCommand(projectPath, command) {
    return $Call.ByID(1244365094, projectPath, command);
}

/**
 * SaveAgent creates or updates an agent entry in config and refreshes the registry.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function SaveAgent(args) {
    return $Call.ByID(1441435542, args);
}

/**
 * SaveChildSession stores a completed child agent session.
 * @param {string} sessionID
 * @param {agent$0.ChildSession | null} child
 * @returns {$CancellablePromise<void>}
 */
export function SaveChildSession(sessionID, child) {
    return $Call.ByID(2829468895, sessionID, child);
}

/**
 * SaveChildSessionToDisk persists a completed child session to disk under
 * the same project as its parent session.
 * @param {string} sessionID
 * @param {agent$0.ChildSession | null} child
 * @returns {$CancellablePromise<void>}
 */
export function SaveChildSessionToDisk(sessionID, child) {
    return $Call.ByID(2797708895, sessionID, child);
}

/**
 * SaveMCPServer creates or updates an MCP server entry in config.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function SaveMCPServer(args) {
    return $Call.ByID(1078817744, args);
}

/**
 * SaveProvider creates or updates a model provider in config.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function SaveProvider(args) {
    return $Call.ByID(3581091756, args);
}

/**
 * SchedulePopupHide starts a debounce to hide the popup.
 * @returns {$CancellablePromise<void>}
 */
export function SchedulePopupHide() {
    return $Call.ByID(294967589);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @param {string} text
 * @param {string} providerID
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(projectPath, sessionID, text, providerID, model) {
    return $Call.ByID(4233179061, projectPath, sessionID, text, providerID, model);
}

/**
 * SendTrayNotification stores a notification and triggers tray blink.
 * @param {string} sessionID
 * @param {string} sessionTitle
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendTrayNotification(sessionID, sessionTitle, message) {
    return $Call.ByID(654018345, sessionID, sessionTitle, message);
}

/**
 * @param {string} providerID
 * @param {string} modelID
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultModel(providerID, modelID) {
    return $Call.ByID(155267082, providerID, modelID);
}

/**
 * SetPermissionMode updates the session-level permission mode ("auto" or "manual").
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function SetPermissionMode(args) {
    return $Call.ByID(2712857384, args);
}

/**
 * SetPipeline stores the permission pipeline reference for runtime mode changes.
 * @param {permission$0.Pipeline | null} p
 * @returns {$CancellablePromise<void>}
 */
export function SetPipeline(p) {
    return $Call.ByID(2022465590, p);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetSessionPinned(projectPath, sessionID, pinned) {
    return $Call.ByID(1945497030, projectPath, sessionID, pinned);
}

/**
 * SetTrayManager sets the tray manager for the application.
 * @param {$models.TrayManager | null} tm
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayManager(tm) {
    return $Call.ByID(3974346431, tm);
}

/**
 * SwitchBranch checks out the given branch in the project.
 * If name starts with "origin/" (remote branch), creates a local tracking branch via git checkout -b.
 * Branch names are validated by validateBranchName to reject names starting with '-'.
 * Automatically stashes tracked changes before checkout and pops them afterward.
 * @param {string} projectPath
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SwitchBranch(projectPath, name) {
    return $Call.ByID(589566188, projectPath, name);
}

/**
 * TestMCPServer attempts to connect a server, list its tools, then disconnect.
 * Returns the list of tool names on success.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<string[]>}
 */
export function TestMCPServer(args) {
    return $Call.ByID(379264411, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * TestMCPServerConfig tests a server config without saving it.
 * It takes the same JSON format as ImportMCPServers but for a single server,
 * connects, lists tools, then disconnects.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<string[]>}
 */
export function TestMCPServerConfig(args) {
    return $Call.ByID(1186287593, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ToggleSkillEnabled toggles the enabled state of a skill by name.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function ToggleSkillEnabled(args) {
    return $Call.ByID(3070293474, args);
}

/**
 * TriggerCompact manually triggers context compaction for a session.
 * @param {string} projectPath
 * @param {string} sessionID
 * @param {string} providerID
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function TriggerCompact(projectPath, sessionID, providerID, model) {
    return $Call.ByID(3450602537, projectPath, sessionID, providerID, model);
}

/**
 * UninstallSkill removes an installed skill by name.
 * @param {json$0.RawMessage} args
 * @returns {$CancellablePromise<void>}
 */
export function UninstallSkill(args) {
    return $Call.ByID(555328523, args);
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(projectPath, filePath, content) {
    return $Call.ByID(677390425, projectPath, filePath, content);
}

// Private type creation functions
const $$createType0 = update$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = update$0.VersionInfo.createFrom;
const $$createType3 = $models.AvailableProviderInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ProjectInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $models.DiffResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = engine$0.Model.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ProviderInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.RecentProject.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.SkillContentResult.createFrom;
const $$createType17 = $models.NotificationData.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = update$0.UpdateStatus.createFrom;
const $$createType20 = $Create.Array($Create.Any);
const $$createType21 = agent$0.Agent.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.BranchInfo.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.ChangeStat.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.FileNode.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.FileChange.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = $models.MCPServerInfo.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = permission$0.Rule.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = $Create.Array($$createType5);
const $$createType36 = $models.SessionInfo.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = engine$0.SkillMeta.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = agent$0.ChildSession.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = $models.Session.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = $Create.Nullable($$createType36);
const $$createType45 = $models.FileContent.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = permission$0.PermissionResponse.createFrom;
