// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelGeneration(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2154546860, sessionID);
}

/**
 * CreateBranch creates and checks out a new branch from the given base branch.
 */
export function CreateBranch(projectPath: string, name: string, baseBranch: string): $CancellablePromise<void> {
    return $Call.ByID(2177215684, projectPath, name, baseBranch);
}

export function DeleteSession(projectPath: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1674819245, projectPath, sessionID);
}

export function GetCurrentProject(): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(4211252234).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetFileDiff(projectPath: string, filePath: string): $CancellablePromise<$models.DiffResult | null> {
    return $Call.ByID(3432667145, projectPath, filePath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetModels(): $CancellablePromise<engine$0.Model[]> {
    return $Call.ByID(2740169318).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetRecentProjects returns recently opened projects from ~/.monika/recent.json.
 */
export function GetRecentProjects(): $CancellablePromise<$models.RecentProject[]> {
    return $Call.ByID(541402157).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListBranches returns local and remote git branches for the given project.
 */
export function ListBranches(projectPath: string): $CancellablePromise<$models.BranchInfo[]> {
    return $Call.ByID(2066625236, projectPath).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListDirectory returns the non-recursive contents of a directory.
 */
export function ListDirectory(parentPath: string): $CancellablePromise<$models.FileNode[]> {
    return $Call.ByID(2022278691, parentPath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListFileChanges(projectPath: string): $CancellablePromise<$models.FileChange[]> {
    return $Call.ByID(3265914211, projectPath).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListFileTree(projectPath: string): $CancellablePromise<$models.FileNode[]> {
    return $Call.ByID(2046651834, projectPath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListProjects(): $CancellablePromise<$models.ProjectInfo[]> {
    return $Call.ByID(1837161474).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListSessions(projectPath: string): $CancellablePromise<$models.SessionInfo[]> {
    return $Call.ByID(116118957, projectPath).then(($result: any) => {
        return $$createType16($result);
    });
}

export function LoadSession(projectPath: string, sessionID: string): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(665171952, projectPath, sessionID).then(($result: any) => {
        return $$createType18($result);
    });
}

export function NewSession(projectPath: string, model: string): $CancellablePromise<$models.SessionInfo | null> {
    return $Call.ByID(3342623882, projectPath, model).then(($result: any) => {
        return $$createType19($result);
    });
}

export function OpenProject(path: string): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(2628211045, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(2270927618);
}

export function ReadFile(projectPath: string, filePath: string): $CancellablePromise<$models.FileContent | null> {
    return $Call.ByID(984933914, projectPath, filePath).then(($result: any) => {
        return $$createType21($result);
    });
}

export function SendMessage(projectPath: string, sessionID: string, text: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(4233179061, projectPath, sessionID, text, model);
}

/**
 * SwitchBranch checks out the given branch in the project.
 * If name starts with "origin/" (remote branch), creates a local tracking branch via git checkout -b.
 * Branch names are validated by validateBranchName to reject names starting with '-'.
 * Automatically stashes tracked changes before checkout and pops them afterward.
 */
export function SwitchBranch(projectPath: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(589566188, projectPath, name);
}

export function WriteFile(projectPath: string, filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(677390425, projectPath, filePath, content);
}

// Private type creation functions
const $$createType0 = $models.ProjectInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DiffResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = engine$0.Model.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.RecentProject.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.BranchInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.FileNode.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.FileChange.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($$createType0);
const $$createType15 = $models.SessionInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.Session.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $Create.Nullable($$createType15);
const $$createType20 = $models.FileContent.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
