// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function CancelGeneration(sessionID) {
    return $Call.ByID(2154546860, sessionID);
}

/**
 * CreateBranch creates and checks out a new branch from the given base branch.
 * @param {string} projectPath
 * @param {string} name
 * @param {string} baseBranch
 * @returns {$CancellablePromise<void>}
 */
export function CreateBranch(projectPath, name, baseBranch) {
    return $Call.ByID(2177215684, projectPath, name, baseBranch);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(projectPath, sessionID) {
    return $Call.ByID(1674819245, projectPath, sessionID);
}

/**
 * @param {string} sessionID
 * @param {agent$0.TaskItem[]} tasks
 * @returns {$CancellablePromise<void>}
 */
export function EmitTaskEvent(sessionID, tasks) {
    return $Call.ByID(1268878478, sessionID, tasks);
}

/**
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function GetCurrentProject() {
    return $Call.ByID(4211252234).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.DiffResult | null>}
 */
export function GetFileDiff(projectPath, filePath) {
    return $Call.ByID(3432667145, projectPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} providerID
 * @returns {$CancellablePromise<engine$0.Model[]>}
 */
export function GetModels(providerID) {
    return $Call.ByID(2740169318, providerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProviderInfo[]>}
 */
export function GetProviders() {
    return $Call.ByID(2466924902).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetRecentProjects returns recently opened projects from ~/.monika/recent.json.
 * @returns {$CancellablePromise<$models.RecentProject[]>}
 */
export function GetRecentProjects() {
    return $Call.ByID(541402157).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListBranches returns local and remote git branches for the given project.
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.BranchInfo[]>}
 */
export function ListBranches(projectPath) {
    return $Call.ByID(2066625236, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.ChangeStat[]>}
 */
export function ListChangeStats(projectPath) {
    return $Call.ByID(2025730651, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * ListDirectory returns the non-recursive contents of a directory.
 * @param {string} parentPath
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function ListDirectory(parentPath) {
    return $Call.ByID(2022278691, parentPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.FileChange[]>}
 */
export function ListFileChanges(projectPath) {
    return $Call.ByID(3265914211, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function ListFileTree(projectPath) {
    return $Call.ByID(2046651834, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProjectInfo[]>}
 */
export function ListProjects() {
    return $Call.ByID(1837161474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} projectPath
 * @returns {$CancellablePromise<$models.SessionInfo[]>}
 */
export function ListSessions(projectPath) {
    return $Call.ByID(116118957, projectPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * LoadChildSession returns a completed child agent session, or nil.
 * @param {string} sessionID
 * @returns {$CancellablePromise<agent$0.ChildSession | null>}
 */
export function LoadChildSession(sessionID) {
    return $Call.ByID(1226969414, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * LoadChildSessionFromDisk loads a completed child session from disk.
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<agent$0.ChildSession | null>}
 */
export function LoadChildSessionFromDisk(projectPath, sessionID) {
    return $Call.ByID(987540711, projectPath, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.Session | null>}
 */
export function LoadSession(projectPath, sessionID) {
    return $Call.ByID(665171952, projectPath, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {string} projectPath
 * @param {string} providerID
 * @param {string} model
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function NewSession(projectPath, providerID, model) {
    return $Call.ByID(3342623882, projectPath, providerID, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<$models.ProjectInfo | null>}
 */
export function OpenProject(path) {
    return $Call.ByID(2628211045, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PendingChildSession stores a child session ID for a parent, so the frontend
 * can resolve it during execution (before the tool returns).
 * @param {string} parentID
 * @param {string} childID
 * @returns {$CancellablePromise<void>}
 */
export function PendingChildSession(parentID, childID) {
    return $Call.ByID(3382073829, parentID, childID);
}

/**
 * @param {string} providerID
 * @param {string} modelID
 * @returns {$CancellablePromise<void>}
 */
export function PersistSelection(providerID, modelID) {
    return $Call.ByID(4057758998, providerID, modelID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(2270927618);
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.FileContent | null>}
 */
export function ReadFile(projectPath, filePath) {
    return $Call.ByID(984933914, projectPath, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * ResolveChildSession returns the latest child session ID for a parent.
 * @param {string} parentID
 * @returns {$CancellablePromise<string>}
 */
export function ResolveChildSession(parentID) {
    return $Call.ByID(3285960262, parentID);
}

/**
 * RunShellCommand executes a shell command in the project directory and returns merged stdout+stderr.
 * @param {string} projectPath
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function RunShellCommand(projectPath, command) {
    return $Call.ByID(4233179062, projectPath, command);
}

/**
 * SaveChildSession stores a completed child agent session.
 * @param {string} sessionID
 * @param {agent$0.ChildSession | null} child
 * @returns {$CancellablePromise<void>}
 */
export function SaveChildSession(sessionID, child) {
    return $Call.ByID(2829468895, sessionID, child);
}

/**
 * SaveChildSessionToDisk persists a completed child session to disk under
 * the same project as its parent session.
 * @param {string} sessionID
 * @param {agent$0.ChildSession | null} child
 * @returns {$CancellablePromise<void>}
 */
export function SaveChildSessionToDisk(sessionID, child) {
    return $Call.ByID(2797708895, sessionID, child);
}

/**
 * @param {string} projectPath
 * @param {string} sessionID
 * @param {string} text
 * @param {string} providerID
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(projectPath, sessionID, text, providerID, model) {
    return $Call.ByID(4233179061, projectPath, sessionID, text, providerID, model);
}

/**
 * SwitchBranch checks out the given branch in the project.
 * If name starts with "origin/" (remote branch), creates a local tracking branch via git checkout -b.
 * Branch names are validated by validateBranchName to reject names starting with '-'.
 * Automatically stashes tracked changes before checkout and pops them afterward.
 * @param {string} projectPath
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SwitchBranch(projectPath, name) {
    return $Call.ByID(589566188, projectPath, name);
}

/**
 * @param {string} projectPath
 * @param {string} filePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(projectPath, filePath, content) {
    return $Call.ByID(677390425, projectPath, filePath, content);
}

// Private type creation functions
const $$createType0 = $models.ProjectInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DiffResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = engine$0.Model.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ProviderInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.RecentProject.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.BranchInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ChangeStat.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.FileNode.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.FileChange.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($$createType0);
const $$createType19 = $models.SessionInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = agent$0.ChildSession.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.Session.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Nullable($$createType19);
const $$createType26 = $models.FileContent.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
