// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPermissionRule adds a new permission rule.
 */
export function AddPermissionRule(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(621401762, args);
}

export function CancelGeneration(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2154546860, sessionID);
}

/**
 * CreateBranch creates and checks out a new branch from the given base branch.
 */
export function CreateBranch(projectPath: string, name: string, baseBranch: string): $CancellablePromise<void> {
    return $Call.ByID(2177215684, projectPath, name, baseBranch);
}

/**
 * DeletePermissionRule removes a rule identified by tool, pattern, and source.
 */
export function DeletePermissionRule(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2803374586, args);
}

export function DeleteSession(projectPath: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1674819245, projectPath, sessionID);
}

export function EmitTaskEvent(sessionID: string, tasks: agent$0.TaskItem[]): $CancellablePromise<void> {
    return $Call.ByID(1268878478, sessionID, tasks);
}

export function GetCurrentProject(): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(4211252234).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetFileDiff(projectPath: string, filePath: string): $CancellablePromise<$models.DiffResult | null> {
    return $Call.ByID(3432667145, projectPath, filePath).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetModels(providerID: string): $CancellablePromise<engine$0.Model[]> {
    return $Call.ByID(2740169318, providerID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetProviders(): $CancellablePromise<$models.ProviderInfo[]> {
    return $Call.ByID(2466924902).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetRecentProjects returns recently opened projects from ~/.monika/recent.json.
 */
export function GetRecentProjects(): $CancellablePromise<$models.RecentProject[]> {
    return $Call.ByID(541402157).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListBranches returns local and remote git branches for the given project.
 */
export function ListBranches(projectPath: string): $CancellablePromise<$models.BranchInfo[]> {
    return $Call.ByID(2066625236, projectPath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListChangeStats(projectPath: string): $CancellablePromise<$models.ChangeStat[]> {
    return $Call.ByID(2025730651, projectPath).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ListDirectory returns the non-recursive contents of a directory.
 */
export function ListDirectory(parentPath: string): $CancellablePromise<$models.FileNode[]> {
    return $Call.ByID(2022278691, parentPath).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListFileChanges(projectPath: string): $CancellablePromise<$models.FileChange[]> {
    return $Call.ByID(3265914211, projectPath).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ListFileTree(projectPath: string): $CancellablePromise<$models.FileNode[]> {
    return $Call.ByID(2046651834, projectPath).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ListPermissionRules returns all permission rules for the given project,
 * including both built-in blacklist rules and user-defined rules.
 */
export function ListPermissionRules(args: json$0.RawMessage): $CancellablePromise<permission$0.Rule[]> {
    return $Call.ByID(1886094366, args).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ListProjects(): $CancellablePromise<$models.ProjectInfo[]> {
    return $Call.ByID(1837161474).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ListSessions(projectPath: string): $CancellablePromise<$models.SessionInfo[]> {
    return $Call.ByID(116118957, projectPath).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * ListSystemCommands searches PATH for executable files matching prefix.
 * Returns up to 20 results, sorted alphabetically.
 */
export function ListSystemCommands(prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(905674791, prefix).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * LoadChildSession returns a completed child agent session, or nil.
 */
export function LoadChildSession(sessionID: string): $CancellablePromise<agent$0.ChildSession | null> {
    return $Call.ByID(1226969414, sessionID).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * LoadChildSessionFromDisk loads a completed child session from disk.
 */
export function LoadChildSessionFromDisk(projectPath: string, sessionID: string): $CancellablePromise<agent$0.ChildSession | null> {
    return $Call.ByID(987540711, projectPath, sessionID).then(($result: any) => {
        return $$createType25($result);
    });
}

export function LoadSession(projectPath: string, sessionID: string): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(665171952, projectPath, sessionID).then(($result: any) => {
        return $$createType27($result);
    });
}

export function NewSession(projectPath: string, providerID: string, model: string): $CancellablePromise<$models.SessionInfo | null> {
    return $Call.ByID(3342623882, projectPath, providerID, model).then(($result: any) => {
        return $$createType28($result);
    });
}

export function OpenProject(path: string): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(2628211045, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PendingChildSession stores a child session ID for a parent, so the frontend
 * can resolve it during execution (before the tool returns).
 */
export function PendingChildSession(parentID: string, childID: string): $CancellablePromise<void> {
    return $Call.ByID(3382073829, parentID, childID);
}

export function PersistSelection(providerID: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(4057758998, providerID, modelID);
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(2270927618);
}

export function ReadFile(projectPath: string, filePath: string): $CancellablePromise<$models.FileContent | null> {
    return $Call.ByID(984933914, projectPath, filePath).then(($result: any) => {
        return $$createType30($result);
    });
}

/**
 * RequestConfirm implements permission.ConfirmUI.
 */
export function RequestConfirm(ev: permission$0.PermissionRequiredEvent): $CancellablePromise<permission$0.PermissionResponse> {
    return $Call.ByID(1950638859, ev).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * ResolveChildSession returns the latest child session ID for a parent.
 */
export function ResolveChildSession(parentID: string): $CancellablePromise<string> {
    return $Call.ByID(3285960262, parentID);
}

/**
 * RespondPermission handles the frontend's response to a permission request.
 */
export function RespondPermission(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3191520234, args);
}

/**
 * RunShellCommand executes a shell command in the project directory and returns merged stdout+stderr.
 * Commands timeout after 120 seconds.
 */
export function RunShellCommand(projectPath: string, command: string): $CancellablePromise<string> {
    return $Call.ByID(1244365094, projectPath, command);
}

/**
 * SaveChildSession stores a completed child agent session.
 */
export function SaveChildSession(sessionID: string, child: agent$0.ChildSession | null): $CancellablePromise<void> {
    return $Call.ByID(2829468895, sessionID, child);
}

/**
 * SaveChildSessionToDisk persists a completed child session to disk under
 * the same project as its parent session.
 */
export function SaveChildSessionToDisk(sessionID: string, child: agent$0.ChildSession | null): $CancellablePromise<void> {
    return $Call.ByID(2797708895, sessionID, child);
}

export function SendMessage(projectPath: string, sessionID: string, text: string, providerID: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(4233179061, projectPath, sessionID, text, providerID, model);
}

/**
 * SetPermissionMode updates the session-level permission mode ("auto" or "manual").
 */
export function SetPermissionMode(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2712857384, args);
}

/**
 * SetPipeline stores the permission pipeline reference for runtime mode changes.
 */
export function SetPipeline(p: permission$0.Pipeline | null): $CancellablePromise<void> {
    return $Call.ByID(2022465590, p);
}

/**
 * SwitchBranch checks out the given branch in the project.
 * If name starts with "origin/" (remote branch), creates a local tracking branch via git checkout -b.
 * Branch names are validated by validateBranchName to reject names starting with '-'.
 * Automatically stashes tracked changes before checkout and pops them afterward.
 */
export function SwitchBranch(projectPath: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(589566188, projectPath, name);
}

export function WriteFile(projectPath: string, filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(677390425, projectPath, filePath, content);
}

// Private type creation functions
const $$createType0 = $models.ProjectInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DiffResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = engine$0.Model.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ProviderInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.RecentProject.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.BranchInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ChangeStat.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.FileNode.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.FileChange.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = permission$0.Rule.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $Create.Array($$createType0);
const $$createType21 = $models.SessionInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($Create.Any);
const $$createType24 = agent$0.ChildSession.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $models.Session.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $Create.Nullable($$createType21);
const $$createType29 = $models.FileContent.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = permission$0.PermissionResponse.createFrom;
