// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPermissionRule adds a new permission rule.
 */
export function AddPermissionRule(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(621401762, args);
}

/**
 * AddSkillPath appends a directory to the skill search paths.
 */
export function AddSkillPath(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(110335, args);
}

/**
 * AppendLoopOption appends a loop option to the internally stored slice.
 */
export function AppendLoopOption(opt: agent$0.LoopOption): $CancellablePromise<void> {
    return $Call.ByID(1912792643, opt);
}

export function ArchiveSession(projectPath: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(457154186, projectPath, sessionID);
}

/**
 * AskUser sends a question to the frontend and blocks until the user responds.
 */
export function AskUser(sessionID: string, question: string, title: string, options: string[]): $CancellablePromise<string> {
    return $Call.ByID(641074198, sessionID, question, title, options);
}

export function CancelGeneration(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2154546860, sessionID);
}

/**
 * CheckForUpdate checks GitHub for the latest release.
 */
export function CheckForUpdate(): $CancellablePromise<update$0.UpdateInfo | null> {
    return $Call.ByID(283735038).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateBranch creates and checks out a new branch from the given base branch.
 */
export function CreateBranch(projectPath: string, name: string, baseBranch: string): $CancellablePromise<void> {
    return $Call.ByID(2177215684, projectPath, name, baseBranch);
}

/**
 * DeleteAgent disables an agent by name (soft-delete via Disabled flag).
 */
export function DeleteAgent(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3042182576, args);
}

/**
 * DeleteMCPServer removes an MCP server entry from config by ID.
 */
export function DeleteMCPServer(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2274596006, args);
}

/**
 * DeletePermissionRule removes a rule identified by tool, pattern, and source.
 */
export function DeletePermissionRule(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2803374586, args);
}

/**
 * DeleteProvider removes a model provider from config by ID.
 */
export function DeleteProvider(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3540968018, args);
}

export function DeleteSession(projectPath: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1674819245, projectPath, sessionID);
}

/**
 * DownloadUpdate downloads the update for the given URL.
 */
export function DownloadUpdate(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2973123721, args);
}

export function EmitTaskEvent(sessionID: string, tasks: agent$0.TaskItem[]): $CancellablePromise<void> {
    return $Call.ByID(1268878478, sessionID, tasks);
}

/**
 * GetAppVersion returns the application version information.
 */
export function GetAppVersion(): $CancellablePromise<update$0.VersionInfo> {
    return $Call.ByID(4174589881).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAvailableProviders returns all providers available from models.dev catalog.
 * This is used in the Settings UI to let users select a provider to add.
 */
export function GetAvailableProviders(): $CancellablePromise<$models.AvailableProviderInfo[]> {
    return $Call.ByID(2025681215).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetCurrentProject(): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(4211252234).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetDefaultModel(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3464228622).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetFileDiff(projectPath: string, filePath: string): $CancellablePromise<$models.DiffResult | null> {
    return $Call.ByID(3432667145, projectPath, filePath).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetInlineDiff(projectPath: string, filePath: string, oldContent: string): $CancellablePromise<$models.DiffResult | null> {
    return $Call.ByID(2333122030, projectPath, filePath, oldContent).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetModels(providerID: string): $CancellablePromise<engine$0.Model[]> {
    return $Call.ByID(2740169318, providerID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetProjectPath returns the current project directory (exported for use by tools).
 */
export function GetProjectPath(): $CancellablePromise<string> {
    return $Call.ByID(2154343474);
}

export function GetProviders(): $CancellablePromise<$models.ProviderInfo[]> {
    return $Call.ByID(2466924902).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetRecentProjects returns recently opened projects from ~/.monika/recent.json.
 */
export function GetRecentProjects(): $CancellablePromise<$models.RecentProject[]> {
    return $Call.ByID(541402157).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetSkillContent returns the SKILL.md content and sibling files for a given skill name.
 */
export function GetSkillContent(args: json$0.RawMessage): $CancellablePromise<$models.SkillContentResult> {
    return $Call.ByID(3735502862, args).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetUpdateStatus returns the current update process status.
 */
export function GetUpdateStatus(): $CancellablePromise<update$0.UpdateStatus> {
    return $Call.ByID(1060979343).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ImportMCPServers parses a standard mcpServers JSON block and adds the servers to config.
 * The input format is: { "mcpServers": { "name": { "type": "stdio", "command": "...", ... } } }
 * Returns the list of server IDs that were imported.
 */
export function ImportMCPServers(args: json$0.RawMessage): $CancellablePromise<string[]> {
    return $Call.ByID(2481263241, args).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * InstallSkillFromURL downloads a GitHub repo and installs skills found in it.
 */
export function InstallSkillFromURL(args: json$0.RawMessage): $CancellablePromise<string[]> {
    return $Call.ByID(3775411401, args).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * InstallSkillFromZip installs skills from a base64-encoded ZIP file.
 */
export function InstallSkillFromZip(args: json$0.RawMessage): $CancellablePromise<string[]> {
    return $Call.ByID(165010839, args).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * InstallUpdate replaces the current binary and restarts.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1856021770);
}

/**
 * ListAgents returns all registered agents.
 */
export function ListAgents(): $CancellablePromise<agent$0.Agent[]> {
    return $Call.ByID(1523826198).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * ListBranches returns local and remote git branches for the given project.
 */
export function ListBranches(projectPath: string): $CancellablePromise<$models.BranchInfo[]> {
    return $Call.ByID(2066625236, projectPath).then(($result: any) => {
        return $$createType22($result);
    });
}

export function ListChangeStats(projectPath: string): $CancellablePromise<$models.ChangeStat[]> {
    return $Call.ByID(2025730651, projectPath).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * ListDirectory returns the non-recursive contents of a directory.
 */
export function ListDirectory(parentPath: string): $CancellablePromise<$models.FileNode[]> {
    return $Call.ByID(2022278691, parentPath).then(($result: any) => {
        return $$createType26($result);
    });
}

export function ListFileChanges(projectPath: string): $CancellablePromise<$models.FileChange[]> {
    return $Call.ByID(3265914211, projectPath).then(($result: any) => {
        return $$createType28($result);
    });
}

export function ListFileTree(projectPath: string, showHidden: boolean): $CancellablePromise<$models.FileNode[]> {
    return $Call.ByID(2046651834, projectPath, showHidden).then(($result: any) => {
        return $$createType26($result);
    });
}

export function ListMCPServers(): $CancellablePromise<$models.MCPServerInfo[]> {
    return $Call.ByID(2784883516).then(($result: any) => {
        return $$createType30($result);
    });
}

/**
 * ListPermissionRules returns all permission rules for the given project,
 * including both built-in blacklist rules and user-defined rules.
 */
export function ListPermissionRules(args: json$0.RawMessage): $CancellablePromise<permission$0.Rule[]> {
    return $Call.ByID(1886094366, args).then(($result: any) => {
        return $$createType32($result);
    });
}

export function ListProjects(): $CancellablePromise<$models.ProjectInfo[]> {
    return $Call.ByID(1837161474).then(($result: any) => {
        return $$createType33($result);
    });
}

export function ListSessions(projectPath: string): $CancellablePromise<$models.SessionInfo[]> {
    return $Call.ByID(116118957, projectPath).then(($result: any) => {
        return $$createType35($result);
    });
}

export function ListSkills(): $CancellablePromise<engine$0.SkillMeta[]> {
    return $Call.ByID(4241996650).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * ListSystemCommands searches PATH for executable files matching prefix.
 * Returns up to 20 results, sorted alphabetically.
 */
export function ListSystemCommands(prefix: string): $CancellablePromise<string[]> {
    return $Call.ByID(905674791, prefix).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * LoadChildSession returns a completed child agent session, or nil.
 */
export function LoadChildSession(sessionID: string): $CancellablePromise<agent$0.ChildSession | null> {
    return $Call.ByID(1226969414, sessionID).then(($result: any) => {
        return $$createType39($result);
    });
}

/**
 * LoadChildSessionFromDisk loads a completed child session from disk.
 */
export function LoadChildSessionFromDisk(projectPath: string, sessionID: string): $CancellablePromise<agent$0.ChildSession | null> {
    return $Call.ByID(987540711, projectPath, sessionID).then(($result: any) => {
        return $$createType39($result);
    });
}

export function LoadSession(projectPath: string, sessionID: string): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(665171952, projectPath, sessionID).then(($result: any) => {
        return $$createType41($result);
    });
}

export function MarkSessionViewed(projectPath: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4285813295, projectPath, sessionID);
}

export function NewSession(projectPath: string, providerID: string, model: string): $CancellablePromise<$models.SessionInfo | null> {
    return $Call.ByID(3342623882, projectPath, providerID, model).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * OpenInFileManager opens the given directory path in the system file manager.
 */
export function OpenInFileManager(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(4046586048, args);
}

export function OpenProject(path: string): $CancellablePromise<$models.ProjectInfo | null> {
    return $Call.ByID(2628211045, path).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PendingChildSession stores a child session ID for a parent, so the frontend
 * can resolve it during execution (before the tool returns).
 */
export function PendingChildSession(parentID: string, childID: string): $CancellablePromise<void> {
    return $Call.ByID(3382073829, parentID, childID);
}

export function PersistSelection(providerID: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(4057758998, providerID, modelID);
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(2270927618);
}

export function ReadFile(projectPath: string, filePath: string): $CancellablePromise<$models.FileContent | null> {
    return $Call.ByID(984933914, projectPath, filePath).then(($result: any) => {
        return $$createType44($result);
    });
}

/**
 * ReconnectMCPServer disconnects and reconnects a configured MCP server,
 * then returns its available tool names.
 */
export function ReconnectMCPServer(args: json$0.RawMessage): $CancellablePromise<string[]> {
    return $Call.ByID(1193347248, args).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * RefreshBranch reads the current git branch from disk and updates in-memory state.
 * Returns the current branch name, or "—" if not a git repo.
 */
export function RefreshBranch(projectPath: string): $CancellablePromise<string> {
    return $Call.ByID(3999763195, projectPath);
}

/**
 * RemoveSkillPath removes a directory from the skill search paths.
 */
export function RemoveSkillPath(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2181192798, args);
}

export function RenameSession(projectPath: string, sessionID: string, newTitle: string): $CancellablePromise<void> {
    return $Call.ByID(3547192606, projectPath, sessionID, newTitle);
}

/**
 * RequestConfirm implements permission.ConfirmUI.
 */
export function RequestConfirm(ev: permission$0.PermissionRequiredEvent): $CancellablePromise<permission$0.PermissionResponse> {
    return $Call.ByID(1950638859, ev).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * ResolveChildSession returns the latest child session ID for a parent.
 */
export function ResolveChildSession(parentID: string): $CancellablePromise<string> {
    return $Call.ByID(3285960262, parentID);
}

/**
 * RespondAskUser handles the frontend's response to an ask_user request.
 */
export function RespondAskUser(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(225985741, args);
}

/**
 * RespondPermission handles the frontend's response to a permission request.
 */
export function RespondPermission(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3191520234, args);
}

/**
 * RunShellCommand executes a shell command in the project directory and returns merged stdout+stderr.
 * Commands timeout after 120 seconds.
 */
export function RunShellCommand(projectPath: string, command: string): $CancellablePromise<string> {
    return $Call.ByID(1244365094, projectPath, command);
}

/**
 * SaveAgent creates or updates an agent entry in config and refreshes the registry.
 */
export function SaveAgent(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(1441435542, args);
}

/**
 * SaveChildSession stores a completed child agent session.
 */
export function SaveChildSession(sessionID: string, child: agent$0.ChildSession | null): $CancellablePromise<void> {
    return $Call.ByID(2829468895, sessionID, child);
}

/**
 * SaveChildSessionToDisk persists a completed child session to disk under
 * the same project as its parent session.
 */
export function SaveChildSessionToDisk(sessionID: string, child: agent$0.ChildSession | null): $CancellablePromise<void> {
    return $Call.ByID(2797708895, sessionID, child);
}

/**
 * SaveMCPServer creates or updates an MCP server entry in config.
 */
export function SaveMCPServer(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(1078817744, args);
}

/**
 * SaveProvider creates or updates a model provider in config.
 */
export function SaveProvider(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3581091756, args);
}

export function SendMessage(projectPath: string, sessionID: string, text: string, providerID: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(4233179061, projectPath, sessionID, text, providerID, model);
}

export function SetDefaultModel(providerID: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(155267082, providerID, modelID);
}

/**
 * SetPermissionMode updates the session-level permission mode ("auto" or "manual").
 */
export function SetPermissionMode(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(2712857384, args);
}

/**
 * SetPipeline stores the permission pipeline reference for runtime mode changes.
 */
export function SetPipeline(p: permission$0.Pipeline | null): $CancellablePromise<void> {
    return $Call.ByID(2022465590, p);
}

export function SetSessionPinned(projectPath: string, sessionID: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(1945497030, projectPath, sessionID, pinned);
}

/**
 * SwitchBranch checks out the given branch in the project.
 * If name starts with "origin/" (remote branch), creates a local tracking branch via git checkout -b.
 * Branch names are validated by validateBranchName to reject names starting with '-'.
 * Automatically stashes tracked changes before checkout and pops them afterward.
 */
export function SwitchBranch(projectPath: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(589566188, projectPath, name);
}

/**
 * TestMCPServer attempts to connect a server, list its tools, then disconnect.
 * Returns the list of tool names on success.
 */
export function TestMCPServer(args: json$0.RawMessage): $CancellablePromise<string[]> {
    return $Call.ByID(379264411, args).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * TestMCPServerConfig tests a server config without saving it.
 * It takes the same JSON format as ImportMCPServers but for a single server,
 * connects, lists tools, then disconnects.
 */
export function TestMCPServerConfig(args: json$0.RawMessage): $CancellablePromise<string[]> {
    return $Call.ByID(1186287593, args).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * ToggleSkillEnabled toggles the enabled state of a skill by name.
 */
export function ToggleSkillEnabled(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(3070293474, args);
}

/**
 * TriggerCompact manually triggers context compaction for a session.
 */
export function TriggerCompact(projectPath: string, sessionID: string, providerID: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(3450602537, projectPath, sessionID, providerID, model);
}

/**
 * UninstallSkill removes an installed skill by name.
 */
export function UninstallSkill(args: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByID(555328523, args);
}

export function WriteFile(projectPath: string, filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(677390425, projectPath, filePath, content);
}

// Private type creation functions
const $$createType0 = update$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = update$0.VersionInfo.createFrom;
const $$createType3 = $models.AvailableProviderInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ProjectInfo.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $models.DiffResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = engine$0.Model.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ProviderInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.RecentProject.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.SkillContentResult.createFrom;
const $$createType17 = update$0.UpdateStatus.createFrom;
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = agent$0.Agent.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.BranchInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.ChangeStat.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.FileNode.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.FileChange.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.MCPServerInfo.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = permission$0.Rule.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $Create.Array($$createType5);
const $$createType34 = $models.SessionInfo.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = engine$0.SkillMeta.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = agent$0.ChildSession.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = $models.Session.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = $Create.Nullable($$createType34);
const $$createType43 = $models.FileContent.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = permission$0.PermissionResponse.createFrom;
