// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tool$0 from "../tool/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * BranchInfo represents a git branch (local or remote).
 */
export class BranchInfo {
    /**
     * Creates a new BranchInfo instance.
     * @param {Partial<BranchInfo>} [$$source = {}] - The source object to create the BranchInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("remote" in $$source)) {
            /**
             * empty = local branch
             * @member
             * @type {string}
             */
            this["remote"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo(/** @type {Partial<BranchInfo>} */($$parsedSource));
    }
}

export class ChangeStat {
    /**
     * Creates a new ChangeStat instance.
     * @param {Partial<ChangeStat>} [$$source = {}] - The source object to create the ChangeStat.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["added"] = 0;
        }
        if (!("deleted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deleted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChangeStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangeStat(/** @type {Partial<ChangeStat>} */($$parsedSource));
    }
}

export class DiffResult {
    /**
     * Creates a new DiffResult instance.
     * @param {Partial<DiffResult>} [$$source = {}] - The source object to create the DiffResult.
     */
    constructor($$source = {}) {
        if (!("file_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_path"] = "";
        }
        if (!("old" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["new"] = "";
        }
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField3_0($$parsedSource["lines"]);
        }
        return new DiffResult(/** @type {Partial<DiffResult>} */($$parsedSource));
    }
}

export class FileChange {
    /**
     * Creates a new FileChange instance.
     * @param {Partial<FileChange>} [$$source = {}] - The source object to create the FileChange.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileChange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange(/** @type {Partial<FileChange>} */($$parsedSource));
    }
}

export class FileChangeEvent {
    /**
     * Creates a new FileChangeEvent instance.
     * @param {Partial<FileChangeEvent>} [$$source = {}] - The source object to create the FileChangeEvent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChangeEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileChangeEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChangeEvent(/** @type {Partial<FileChangeEvent>} */($$parsedSource));
    }
}

export class FileContent {
    /**
     * Creates a new FileContent instance.
     * @param {Partial<FileContent>} [$$source = {}] - The source object to create the FileContent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("exist" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileContent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent(/** @type {Partial<FileContent>} */($$parsedSource));
    }
}

export class FileNode {
    /**
     * Creates a new FileNode instance.
     * @param {Partial<FileNode>} [$$source = {}] - The source object to create the FileNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("is_dir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dir"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileNode[] | undefined}
             */
            this["children"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileNode}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FileNode(/** @type {Partial<FileNode>} */($$parsedSource));
    }
}

export class ProjectInfo {
    /**
     * Creates a new ProjectInfo instance.
     * @param {Partial<ProjectInfo>} [$$source = {}] - The source object to create the ProjectInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("worktrees" in $$source)) {
            /**
             * @member
             * @type {WorktreeInfo[]}
             */
            this["worktrees"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("worktrees" in $$parsedSource) {
            $$parsedSource["worktrees"] = $$createField3_0($$parsedSource["worktrees"]);
        }
        return new ProjectInfo(/** @type {Partial<ProjectInfo>} */($$parsedSource));
    }
}

/**
 * ProviderInfo identifies a configured provider for the frontend selector.
 */
export class ProviderInfo {
    /**
     * Creates a new ProviderInfo instance.
     * @param {Partial<ProviderInfo>} [$$source = {}] - The source object to create the ProviderInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderInfo(/** @type {Partial<ProviderInfo>} */($$parsedSource));
    }
}

/**
 * RecentProject represents a recently opened project.
 */
export class RecentProject {
    /**
     * Creates a new RecentProject instance.
     * @param {Partial<RecentProject>} [$$source = {}] - The source object to create the RecentProject.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("opened_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["opened_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentProject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentProject}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentProject(/** @type {Partial<RecentProject>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("project_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_dir"] = "";
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {engine$0.ChatMessage[]}
             */
            this["messages"] = [];
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_max"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["compaction_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {engine$0.ChatMessage[] | undefined}
             */
            this["archived_messages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parent_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {tool$0.Task[] | undefined}
             */
            this["tasks"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        const $$createField10_0 = $$createType6;
        const $$createField12_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField3_0($$parsedSource["messages"]);
        }
        if ("archived_messages" in $$parsedSource) {
            $$parsedSource["archived_messages"] = $$createField10_0($$parsedSource["archived_messages"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField12_0($$parsedSource["tasks"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_max"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

export class StreamEvent {
    /**
     * Creates a new StreamEvent instance.
     * @param {Partial<StreamEvent>} [$$source = {}] - The source object to create the StreamEvent.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["session_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.ToolEvent | null | undefined}
             */
            this["tool"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.UsageEvent | null | undefined}
             */
            this["usage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileChangeEvent | null | undefined}
             */
            this["file_change"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.CompactingEvent | null | undefined}
             */
            this["compacting"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.CompactionEvent | null | undefined}
             */
            this["compaction"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.TaskItem[] | undefined}
             */
            this["tasks"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {permission$0.PermissionRequiredEvent | null | undefined}
             */
            this["permission"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamEvent}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType12;
        const $$createField6_0 = $$createType14;
        const $$createField7_0 = $$createType16;
        const $$createField8_0 = $$createType18;
        const $$createField9_0 = $$createType20;
        const $$createField10_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField4_0($$parsedSource["tool"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField5_0($$parsedSource["usage"]);
        }
        if ("file_change" in $$parsedSource) {
            $$parsedSource["file_change"] = $$createField6_0($$parsedSource["file_change"]);
        }
        if ("compacting" in $$parsedSource) {
            $$parsedSource["compacting"] = $$createField7_0($$parsedSource["compacting"]);
        }
        if ("compaction" in $$parsedSource) {
            $$parsedSource["compaction"] = $$createField8_0($$parsedSource["compaction"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField9_0($$parsedSource["tasks"]);
        }
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField10_0($$parsedSource["permission"]);
        }
        return new StreamEvent(/** @type {Partial<StreamEvent>} */($$parsedSource));
    }
}

export class WorktreeInfo {
    /**
     * Creates a new WorktreeInfo instance.
     * @param {Partial<WorktreeInfo>} [$$source = {}] - The source object to create the WorktreeInfo.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktreeInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorktreeInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktreeInfo(/** @type {Partial<WorktreeInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FileNode.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = WorktreeInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = engine$0.ChatMessage.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = tool$0.Task.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = agent$0.ToolEvent.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = agent$0.UsageEvent.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = FileChangeEvent.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = agent$0.CompactingEvent.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = agent$0.CompactionEvent.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = agent$0.TaskItem.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = permission$0.PermissionRequiredEvent.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
