// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * BranchInfo represents a git branch (local or remote).
 */
export class BranchInfo {
    "name": string;

    /**
     * empty = local branch
     */
    "remote": string;

    /** Creates a new BranchInfo instance. */
    constructor($$source: Partial<BranchInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("remote" in $$source)) {
            this["remote"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo($$parsedSource as Partial<BranchInfo>);
    }
}

export class DiffResult {
    "file_path": string;
    "old": string;
    "new": string;
    "lines": string[];

    /** Creates a new DiffResult instance. */
    constructor($$source: Partial<DiffResult> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("old" in $$source)) {
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            this["new"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffResult {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField3_0($$parsedSource["lines"]);
        }
        return new DiffResult($$parsedSource as Partial<DiffResult>);
    }
}

export class FileChange {
    "path": string;
    "status": string;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

export class FileChangeEvent {
    "path": string;
    "status": string;

    /** Creates a new FileChangeEvent instance. */
    constructor($$source: Partial<FileChangeEvent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChangeEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChangeEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChangeEvent($$parsedSource as Partial<FileChangeEvent>);
    }
}

export class FileContent {
    "path": string;
    "content": string;
    "exist": boolean;

    /** Creates a new FileContent instance. */
    constructor($$source: Partial<FileContent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("exist" in $$source)) {
            this["exist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent($$parsedSource as Partial<FileContent>);
    }
}

export class FileNode {
    "name": string;
    "path": string;
    "is_dir": boolean;
    "children"?: FileNode[];
    "status"?: string;

    /** Creates a new FileNode instance. */
    constructor($$source: Partial<FileNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FileNode {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FileNode($$parsedSource as Partial<FileNode>);
    }
}

export class ProjectInfo {
    "path": string;
    "name": string;
    "branch": string;
    "worktrees": WorktreeInfo[];

    /** Creates a new ProjectInfo instance. */
    constructor($$source: Partial<ProjectInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("worktrees" in $$source)) {
            this["worktrees"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectInfo {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("worktrees" in $$parsedSource) {
            $$parsedSource["worktrees"] = $$createField3_0($$parsedSource["worktrees"]);
        }
        return new ProjectInfo($$parsedSource as Partial<ProjectInfo>);
    }
}

/**
 * RecentProject represents a recently opened project.
 */
export class RecentProject {
    "path": string;
    "name": string;
    "opened_at": number;

    /** Creates a new RecentProject instance. */
    constructor($$source: Partial<RecentProject> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("opened_at" in $$source)) {
            this["opened_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentProject instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentProject($$parsedSource as Partial<RecentProject>);
    }
}

export class Session {
    "id": string;
    "title": string;
    "project_dir": string;
    "messages": engine$0.ChatMessage[];
    "model": string;
    "provider": string;
    "status": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("project_dir" in $$source)) {
            this["project_dir"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField3_0($$parsedSource["messages"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionInfo {
    "id": string;
    "title": string;
    "status": string;
    "updated_at": string;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

export class StreamEvent {
    "type": string;
    "content"?: string;
    "session_id"?: string;
    "model"?: string;
    "tool"?: agent$0.ToolEvent | null;
    "usage"?: agent$0.UsageEvent | null;
    "file_change"?: FileChangeEvent | null;
    "compacting"?: any;
    "compaction"?: any;
    "tasks"?: any[];

    /** Creates a new StreamEvent instance. */
    constructor($$source: Partial<StreamEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamEvent {
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField4_0($$parsedSource["tool"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField5_0($$parsedSource["usage"]);
        }
        if ("file_change" in $$parsedSource) {
            $$parsedSource["file_change"] = $$createField6_0($$parsedSource["file_change"]);
        }
        return new StreamEvent($$parsedSource as Partial<StreamEvent>);
    }
}

export class WorktreeInfo {
    "branch": string;
    "path": string;

    /** Creates a new WorktreeInfo instance. */
    constructor($$source: Partial<WorktreeInfo> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktreeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktreeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktreeInfo($$parsedSource as Partial<WorktreeInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FileNode.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = WorktreeInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = engine$0.ChatMessage.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = agent$0.ToolEvent.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = agent$0.UsageEvent.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = FileChangeEvent.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
