// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tool$0 from "../tool/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AskUserEvent {
    /**
     * Creates a new AskUserEvent instance.
     * @param {Partial<AskUserEvent>} [$$source = {}] - The source object to create the AskUserEvent.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("question" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["question"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AskUserEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AskUserEvent}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new AskUserEvent(/** @type {Partial<AskUserEvent>} */($$parsedSource));
    }
}

/**
 * AvailableModelInfo represents a model from models.dev.
 */
export class AvailableModelInfo {
    /**
     * Creates a new AvailableModelInfo instance.
     * @param {Partial<AvailableModelInfo>} [$$source = {}] - The source object to create the AvailableModelInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("context_limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["context_limit"] = 0;
        }
        if (!("output_limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["output_limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AvailableModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailableModelInfo(/** @type {Partial<AvailableModelInfo>} */($$parsedSource));
    }
}

/**
 * AvailableProviderInfo represents a provider available from models.dev for users to add.
 */
export class AvailableProviderInfo {
    /**
     * Creates a new AvailableProviderInfo instance.
     * @param {Partial<AvailableProviderInfo>} [$$source = {}] - The source object to create the AvailableProviderInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("npm" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["npm"] = "";
        }
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {AvailableModelInfo[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableProviderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AvailableProviderInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField4_0($$parsedSource["models"]);
        }
        return new AvailableProviderInfo(/** @type {Partial<AvailableProviderInfo>} */($$parsedSource));
    }
}

/**
 * BranchInfo represents a git branch (local or remote).
 */
export class BranchInfo {
    /**
     * Creates a new BranchInfo instance.
     * @param {Partial<BranchInfo>} [$$source = {}] - The source object to create the BranchInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("remote" in $$source)) {
            /**
             * empty = local branch
             * @member
             * @type {string}
             */
            this["remote"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo(/** @type {Partial<BranchInfo>} */($$parsedSource));
    }
}

export class ChangeStat {
    /**
     * Creates a new ChangeStat instance.
     * @param {Partial<ChangeStat>} [$$source = {}] - The source object to create the ChangeStat.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["added"] = 0;
        }
        if (!("deleted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deleted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChangeStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangeStat(/** @type {Partial<ChangeStat>} */($$parsedSource));
    }
}

export class DiffResult {
    /**
     * Creates a new DiffResult instance.
     * @param {Partial<DiffResult>} [$$source = {}] - The source object to create the DiffResult.
     */
    constructor($$source = {}) {
        if (!("file_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file_path"] = "";
        }
        if (!("old" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["new"] = "";
        }
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField3_0($$parsedSource["lines"]);
        }
        return new DiffResult(/** @type {Partial<DiffResult>} */($$parsedSource));
    }
}

export class FileChange {
    /**
     * Creates a new FileChange instance.
     * @param {Partial<FileChange>} [$$source = {}] - The source object to create the FileChange.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileChange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange(/** @type {Partial<FileChange>} */($$parsedSource));
    }
}

export class FileChangeEvent {
    /**
     * Creates a new FileChangeEvent instance.
     * @param {Partial<FileChangeEvent>} [$$source = {}] - The source object to create the FileChangeEvent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChangeEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileChangeEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChangeEvent(/** @type {Partial<FileChangeEvent>} */($$parsedSource));
    }
}

export class FileContent {
    /**
     * Creates a new FileContent instance.
     * @param {Partial<FileContent>} [$$source = {}] - The source object to create the FileContent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("exist" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileContent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent(/** @type {Partial<FileContent>} */($$parsedSource));
    }
}

export class FileNode {
    /**
     * Creates a new FileNode instance.
     * @param {Partial<FileNode>} [$$source = {}] - The source object to create the FileNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("is_dir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dir"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileNode[] | undefined}
             */
            this["children"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileNode}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FileNode(/** @type {Partial<FileNode>} */($$parsedSource));
    }
}

/**
 * MCPServerInfo describes a configured MCP server and its connection status.
 */
export class MCPServerInfo {
    /**
     * Creates a new MCPServerInfo instance.
     * @param {Partial<MCPServerInfo>} [$$source = {}] - The source object to create the MCPServerInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["args"] = [];
        }
        if (!("env" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["env"] = {};
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("status" in $$source)) {
            /**
             * "connected" | "disconnected"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MCPServerInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType5;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        return new MCPServerInfo(/** @type {Partial<MCPServerInfo>} */($$parsedSource));
    }
}

export class ModelEntryJSON {
    /**
     * Creates a new ModelEntryJSON instance.
     * @param {Partial<ModelEntryJSON>} [$$source = {}] - The source object to create the ModelEntryJSON.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["context_limit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["output_limit"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelEntryJSON instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelEntryJSON}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelEntryJSON(/** @type {Partial<ModelEntryJSON>} */($$parsedSource));
    }
}

/**
 * NotificationData represents a single notification for the tray popup.
 */
export class NotificationData {
    /**
     * Creates a new NotificationData instance.
     * @param {Partial<NotificationData>} [$$source = {}] - The source object to create the NotificationData.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("session_title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_title"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotificationData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationData(/** @type {Partial<NotificationData>} */($$parsedSource));
    }
}

export class ProjectInfo {
    /**
     * Creates a new ProjectInfo instance.
     * @param {Partial<ProjectInfo>} [$$source = {}] - The source object to create the ProjectInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("worktrees" in $$source)) {
            /**
             * @member
             * @type {WorktreeInfo[]}
             */
            this["worktrees"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("worktrees" in $$parsedSource) {
            $$parsedSource["worktrees"] = $$createField3_0($$parsedSource["worktrees"]);
        }
        return new ProjectInfo(/** @type {Partial<ProjectInfo>} */($$parsedSource));
    }
}

/**
 * ProviderInfo identifies a configured provider for the frontend selector.
 */
export class ProviderInfo {
    /**
     * Creates a new ProviderInfo instance.
     * @param {Partial<ProviderInfo>} [$$source = {}] - The source object to create the ProviderInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["wire_api"] = undefined;
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ModelEntryJSON[]}
             */
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField5_0($$parsedSource["models"]);
        }
        return new ProviderInfo(/** @type {Partial<ProviderInfo>} */($$parsedSource));
    }
}

/**
 * RecentProject represents a recently opened project.
 */
export class RecentProject {
    /**
     * Creates a new RecentProject instance.
     * @param {Partial<RecentProject>} [$$source = {}] - The source object to create the RecentProject.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("opened_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["opened_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentProject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentProject}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentProject(/** @type {Partial<RecentProject>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["custom_title"] = undefined;
        }
        if (!("project_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project_dir"] = "";
        }
        if (!("messages" in $$source)) {
            /**
             * @member
             * @type {engine$0.ChatMessage[]}
             */
            this["messages"] = [];
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_max"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["compaction_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["compaction_from"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parent_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {tool$0.Task[] | undefined}
             */
            this["tasks"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["last_viewed_at"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType11;
        const $$createField14_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField4_0($$parsedSource["messages"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField14_0($$parsedSource["tasks"]);
        }
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["token_max"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

/**
 * SkillContentResult is the API response for GetSkillContent.
 */
export class SkillContentResult {
    /**
     * Creates a new SkillContentResult instance.
     * @param {Partial<SkillContentResult>} [$$source = {}] - The source object to create the SkillContentResult.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillContentResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillContentResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new SkillContentResult(/** @type {Partial<SkillContentResult>} */($$parsedSource));
    }
}

export class StreamEvent {
    /**
     * Creates a new StreamEvent instance.
     * @param {Partial<StreamEvent>} [$$source = {}] - The source object to create the StreamEvent.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["session_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["seq"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.ToolEvent | null | undefined}
             */
            this["tool"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.UsageEvent | null | undefined}
             */
            this["usage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileChangeEvent | null | undefined}
             */
            this["file_change"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.CompactionEvent | null | undefined}
             */
            this["compaction"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {agent$0.TaskItem[] | undefined}
             */
            this["tasks"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {permission$0.PermissionRequiredEvent | null | undefined}
             */
            this["permission"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AskUserEvent | null | undefined}
             */
            this["ask_user"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamEvent}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType17;
        const $$createField7_0 = $$createType19;
        const $$createField8_0 = $$createType21;
        const $$createField9_0 = $$createType23;
        const $$createField10_0 = $$createType25;
        const $$createField11_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField5_0($$parsedSource["tool"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField6_0($$parsedSource["usage"]);
        }
        if ("file_change" in $$parsedSource) {
            $$parsedSource["file_change"] = $$createField7_0($$parsedSource["file_change"]);
        }
        if ("compaction" in $$parsedSource) {
            $$parsedSource["compaction"] = $$createField8_0($$parsedSource["compaction"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField9_0($$parsedSource["tasks"]);
        }
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField10_0($$parsedSource["permission"]);
        }
        if ("ask_user" in $$parsedSource) {
            $$parsedSource["ask_user"] = $$createField11_0($$parsedSource["ask_user"]);
        }
        return new StreamEvent(/** @type {Partial<StreamEvent>} */($$parsedSource));
    }
}

export class TrayManager {
    /**
     * Creates a new TrayManager instance.
     * @param {Partial<TrayManager>} [$$source = {}] - The source object to create the TrayManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrayManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrayManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrayManager(/** @type {Partial<TrayManager>} */($$parsedSource));
    }
}

export class WorktreeInfo {
    /**
     * Creates a new WorktreeInfo instance.
     * @param {Partial<WorktreeInfo>} [$$source = {}] - The source object to create the WorktreeInfo.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktreeInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorktreeInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktreeInfo(/** @type {Partial<WorktreeInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AvailableModelInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FileNode.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = WorktreeInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ModelEntryJSON.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = engine$0.ChatMessage.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = tool$0.Task.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = agent$0.ToolEvent.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = agent$0.UsageEvent.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = FileChangeEvent.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = agent$0.CompactionEvent.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = agent$0.TaskItem.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = permission$0.PermissionRequiredEvent.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = AskUserEvent.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
