// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tool$0 from "../tool/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../pkg/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AskUserEvent {
    "requestId": string;
    "sessionId": string;
    "question": string;
    "title"?: string;
    "options"?: string[];

    /** Creates a new AskUserEvent instance. */
    constructor($$source: Partial<AskUserEvent> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("question" in $$source)) {
            this["question"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AskUserEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AskUserEvent {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new AskUserEvent($$parsedSource as Partial<AskUserEvent>);
    }
}

/**
 * AvailableModelInfo represents a model from models.dev.
 */
export class AvailableModelInfo {
    "id": string;
    "name": string;
    "context_limit": number;
    "output_limit": number;

    /** Creates a new AvailableModelInfo instance. */
    constructor($$source: Partial<AvailableModelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("context_limit" in $$source)) {
            this["context_limit"] = 0;
        }
        if (!("output_limit" in $$source)) {
            this["output_limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AvailableModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailableModelInfo($$parsedSource as Partial<AvailableModelInfo>);
    }
}

/**
 * AvailableProviderInfo represents a provider available from models.dev for users to add.
 */
export class AvailableProviderInfo {
    "id": string;
    "display_name": string;
    "npm": string;
    "base_url": string;
    "models": AvailableModelInfo[];

    /** Creates a new AvailableProviderInfo instance. */
    constructor($$source: Partial<AvailableProviderInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("npm" in $$source)) {
            this["npm"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableProviderInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AvailableProviderInfo {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField4_0($$parsedSource["models"]);
        }
        return new AvailableProviderInfo($$parsedSource as Partial<AvailableProviderInfo>);
    }
}

/**
 * BranchInfo represents a git branch (local or remote).
 */
export class BranchInfo {
    "name": string;

    /**
     * empty = local branch
     */
    "remote": string;

    /** Creates a new BranchInfo instance. */
    constructor($$source: Partial<BranchInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("remote" in $$source)) {
            this["remote"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo($$parsedSource as Partial<BranchInfo>);
    }
}

export class ChangeStat {
    "path": string;
    "added": number;
    "deleted": number;

    /** Creates a new ChangeStat instance. */
    constructor($$source: Partial<ChangeStat> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("added" in $$source)) {
            this["added"] = 0;
        }
        if (!("deleted" in $$source)) {
            this["deleted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeStat instance from a string or object.
     */
    static createFrom($$source: any = {}): ChangeStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChangeStat($$parsedSource as Partial<ChangeStat>);
    }
}

export class DiffResult {
    "file_path": string;
    "old": string;
    "new": string;
    "lines": string[];

    /** Creates a new DiffResult instance. */
    constructor($$source: Partial<DiffResult> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("old" in $$source)) {
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            this["new"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffResult {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField3_0($$parsedSource["lines"]);
        }
        return new DiffResult($$parsedSource as Partial<DiffResult>);
    }
}

export class FileChange {
    "path": string;
    "status": string;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

export class FileChangeEvent {
    "path": string;
    "status": string;

    /** Creates a new FileChangeEvent instance. */
    constructor($$source: Partial<FileChangeEvent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChangeEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChangeEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChangeEvent($$parsedSource as Partial<FileChangeEvent>);
    }
}

export class FileContent {
    "path": string;
    "content": string;
    "exist": boolean;

    /** Creates a new FileContent instance. */
    constructor($$source: Partial<FileContent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("exist" in $$source)) {
            this["exist"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent($$parsedSource as Partial<FileContent>);
    }
}

export class FileNode {
    "name": string;
    "path": string;
    "is_dir": boolean;
    "children"?: FileNode[];
    "status"?: string;

    /** Creates a new FileNode instance. */
    constructor($$source: Partial<FileNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FileNode {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FileNode($$parsedSource as Partial<FileNode>);
    }
}

/**
 * MCPServerInfo describes a configured MCP server and its connection status.
 */
export class MCPServerInfo {
    "id": string;
    "type": string;
    "command": string;
    "args": string[];
    "env": { [_ in string]?: string };
    "url": string;
    "headers": { [_ in string]?: string };

    /**
     * "connected" | "disconnected"
     */
    "status": string;

    /** Creates a new MCPServerInfo instance. */
    constructor($$source: Partial<MCPServerInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPServerInfo {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType5;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        return new MCPServerInfo($$parsedSource as Partial<MCPServerInfo>);
    }
}

export class ModelEntryJSON {
    "id": string;
    "name": string;
    "context_limit"?: number;
    "output_limit"?: number;
    "enabled": boolean;

    /** Creates a new ModelEntryJSON instance. */
    constructor($$source: Partial<ModelEntryJSON> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelEntryJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelEntryJSON {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelEntryJSON($$parsedSource as Partial<ModelEntryJSON>);
    }
}

/**
 * NotificationData represents a single notification for the tray popup.
 */
export class NotificationData {
    "id": string;
    "session_id": string;
    "session_title": string;
    "type": string;
    "message": string;
    "timestamp": number;

    /** Creates a new NotificationData instance. */
    constructor($$source: Partial<NotificationData> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("session_title" in $$source)) {
            this["session_title"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationData instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationData($$parsedSource as Partial<NotificationData>);
    }
}

export class ProjectInfo {
    "path": string;
    "name": string;
    "branch": string;
    "worktrees": WorktreeInfo[];

    /** Creates a new ProjectInfo instance. */
    constructor($$source: Partial<ProjectInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("worktrees" in $$source)) {
            this["worktrees"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectInfo {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("worktrees" in $$parsedSource) {
            $$parsedSource["worktrees"] = $$createField3_0($$parsedSource["worktrees"]);
        }
        return new ProjectInfo($$parsedSource as Partial<ProjectInfo>);
    }
}

/**
 * ProviderInfo identifies a configured provider for the frontend selector.
 */
export class ProviderInfo {
    "id": string;
    "display_name": string;
    "base_url": string;
    "api_key": string;
    "wire_api"?: string;
    "models": ModelEntryJSON[];

    /** Creates a new ProviderInfo instance. */
    constructor($$source: Partial<ProviderInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderInfo {
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField5_0($$parsedSource["models"]);
        }
        return new ProviderInfo($$parsedSource as Partial<ProviderInfo>);
    }
}

/**
 * RecentProject represents a recently opened project.
 */
export class RecentProject {
    "path": string;
    "name": string;
    "opened_at": number;

    /** Creates a new RecentProject instance. */
    constructor($$source: Partial<RecentProject> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("opened_at" in $$source)) {
            this["opened_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentProject instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentProject($$parsedSource as Partial<RecentProject>);
    }
}

export class Session {
    "id": string;
    "title": string;
    "custom_title"?: boolean;
    "project_dir": string;
    "messages": engine$0.ChatMessage[];
    "model": string;
    "provider": string;
    "status": string;
    "pinned": boolean;
    "token_count"?: number;
    "token_max"?: number;
    "compaction_count"?: number;
    "compaction_from"?: number;
    "parent_id"?: string;
    "tasks"?: tool$0.Task[];
    "last_viewed_at"?: time$0.Time | null;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("project_dir" in $$source)) {
            this["project_dir"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField4_0 = $$createType11;
        const $$createField14_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField4_0($$parsedSource["messages"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField14_0($$parsedSource["tasks"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionInfo {
    "id": string;
    "title": string;
    "status": string;
    "pinned": boolean;
    "updated_at": string;
    "token_count"?: number;
    "token_max"?: number;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

/**
 * SkillContentResult is the API response for GetSkillContent.
 */
export class SkillContentResult {
    "content": string;
    "files": string[];

    /** Creates a new SkillContentResult instance. */
    constructor($$source: Partial<SkillContentResult> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillContentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillContentResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new SkillContentResult($$parsedSource as Partial<SkillContentResult>);
    }
}

export class StreamEvent {
    "type": string;
    "content"?: string;
    "session_id"?: string;
    "model"?: string;
    "seq"?: number;
    "tool"?: agent$0.ToolEvent | null;
    "usage"?: agent$0.UsageEvent | null;
    "file_change"?: FileChangeEvent | null;
    "compaction"?: agent$0.CompactionEvent | null;
    "tasks"?: agent$0.TaskItem[];
    "permission"?: permission$0.PermissionRequiredEvent | null;
    "ask_user"?: AskUserEvent | null;

    /** Creates a new StreamEvent instance. */
    constructor($$source: Partial<StreamEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamEvent {
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType17;
        const $$createField7_0 = $$createType19;
        const $$createField8_0 = $$createType21;
        const $$createField9_0 = $$createType23;
        const $$createField10_0 = $$createType25;
        const $$createField11_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField5_0($$parsedSource["tool"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField6_0($$parsedSource["usage"]);
        }
        if ("file_change" in $$parsedSource) {
            $$parsedSource["file_change"] = $$createField7_0($$parsedSource["file_change"]);
        }
        if ("compaction" in $$parsedSource) {
            $$parsedSource["compaction"] = $$createField8_0($$parsedSource["compaction"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField9_0($$parsedSource["tasks"]);
        }
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField10_0($$parsedSource["permission"]);
        }
        if ("ask_user" in $$parsedSource) {
            $$parsedSource["ask_user"] = $$createField11_0($$parsedSource["ask_user"]);
        }
        return new StreamEvent($$parsedSource as Partial<StreamEvent>);
    }
}

export class TrayManager {

    /** Creates a new TrayManager instance. */
    constructor($$source: Partial<TrayManager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrayManager instance from a string or object.
     */
    static createFrom($$source: any = {}): TrayManager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrayManager($$parsedSource as Partial<TrayManager>);
    }
}

export class WorktreeInfo {
    "branch": string;
    "path": string;

    /** Creates a new WorktreeInfo instance. */
    constructor($$source: Partial<WorktreeInfo> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktreeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktreeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktreeInfo($$parsedSource as Partial<WorktreeInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AvailableModelInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FileNode.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = WorktreeInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ModelEntryJSON.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = engine$0.ChatMessage.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = tool$0.Task.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = agent$0.ToolEvent.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = agent$0.UsageEvent.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = FileChangeEvent.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = agent$0.CompactionEvent.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = agent$0.TaskItem.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = permission$0.PermissionRequiredEvent.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = AskUserEvent.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
