// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as api$0 from "../../../../../monika/internal/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as update$0 from "../../../../../monika/internal/update/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "branch-changed": string;
            "stream": api$0.StreamEvent;
            "update-available": update$0.UpdateInfo;
        }
    }
}
