// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Task {
    "id": string;
    "subject": string;
    "description"?: string;
    "status": string;
    "blockedBy"?: string[];

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockedBy" in $$parsedSource) {
            $$parsedSource["blockedBy"] = $$createField4_0($$parsedSource["blockedBy"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
